### ISSUE TITLE
number of columns when plotting

### ISSUE THREAD

**Issue by slhandler** [monte-flora/py-mint#27]
Number of columns for plotting should be done behind the scenes. Propose changing to something like below within base_plotting.py create_subplots()

        if n_panels >= 10:
            n_columns = 4
        elif ((n_panels == 3) or ((n_panels >= 5) and (n_panels < 10))):
            n_columns = 3
        elif ((n_panels == 2) or (n_panels == 4)):
            n_columns = 2
        else:
            n_columns = 1

        # print warning if number of features to plot > 16
        if n_panels > 16:
            print("Current number of features %s may not result in nice plot. \n
                   Suggest creating multiple plots of smaller features." % (n_panels))

The above would replace

        if n_panels <= 3:
            n_columns = n_panels
            delete = False
        else:
            n_columns = kwargs.get("n_columns", 3)

**Comment by monte-flora** [comment]
I have introduced a more general framework for determining the number of columns. I've also updated the code so that the user can manually declare the number of columns when making multi-panel plots.
