### ISSUE TITLE
Wrong attribute name in tutorial's datafile

### ISSUE THREAD

**Issue by jvpeetz** [monte-flora/py-mint#65]
Hi,
trying out the tutorial notebook `accumulated_local_effect_tutorial.ipynb` leads to an error in the line
```
results = explainer.load(fnames='multipass_importance_naupdc.nc')
```
It gives `KeyError: 'estimator_output'` from line
```
-> 1849             setattr(s, 'estimator_output', results.attrs['estimator_output'])
```
in file `main/interpret_toolkit.py`.
This is due to mis-named attributes in the input data file `multipass_importance_naupdc.nc`. It should have attributes `estimator_output` and `estimators used` instead of `model_output` and `models used` I think.
Regards, J-V Peetz.

**Comment by monte-flora** [comment]
Sorry about that. I forgot to push the latest versions of the multi-pass result NetCDF files. I've added the updated files and the tutorial notebook should work now. Let me know if you have any further issues!

**Comment by jvpeetz** [comment]
Yes, the multi-pass result NetCDF file now works. Thank you very much for all your work, `py-mint` is a very nice tool for XAI. There's another problem in the tutorial notebook which I will address in a new issue.
