### ISSUE TITLE
Crash in notebook `accumulated_local_effects_tutorial.ipynb`

### ISSUE THREAD

**Issue by jvpeetz** [monte-flora/py-mint#86]
I also took a look at your tutorial notebook `accumulated_local_effects_tutorial.ipynb` again, using the following Python module versions:

- pandas: 1.1.5
- scikit-learn: 1.0.2
- shap: 0.40.0
- py-mint: 0.2.6

The current scikit-learn version 1.1 would need additional adaptions.
The function `plot_importance()` now needs an additional parameter `panels`. The description in the source code `main/interpret_toolkit.py` also needs an update.
In cell [17] the parameter `plot_correlated_features` must be kept at its default value `False`. I just commented it out. 
The function `main_effect_complexity()` prints out a long warning and no result. The remedy suggested in the warning seems to work. I patched the file `main/global_interpret.py` as follows:
```
--- global_interpret.py.orig	2022-07-12 21:21:48.297214577 +0200
+++ global_interpret.py	2022-07-21 12:16:23.558855096 +0200
@@ -14,6 +14,8 @@
 from joblib import delayed, Parallel
 
 
+from sklearn.pipeline import make_pipeline
+from sklearn.preprocessing import StandardScaler
 from sklearn.linear_model import LinearRegression
 from sklearn import cluster
 from sklearn.metrics import (
@@ -1959,7 +1961,7 @@
                                [range(temp_breaks[i], temp_breaks[i+1]+1) for i in range(len(temp_breaks)-1)] +\
                                [range(temp_breaks[-1], b_max)]
 
-                        estimator_set = [LinearRegression(normalize=True) for _ in range(len(idxs_set))]
+                        estimator_set = [make_pipeline(StandardScaler(with_mean=False), LinearRegression()) for _ in range(len(idxs_set))]
                         
                         estimator_fit_set_tmp = [estimator_set[i].fit(x[idxs,:], ale[idxs])
                                              for i, idxs in enumerate(idxs_set)
```
What do you think?. I'm thankful for your efforts and progress with this project.
Regards,
Jörg.

**Comment by monte-flora** [comment]
I'm glad that you are finding this package useful! Yes, including that pipeline with StandardScaler addresses this issue. I will note that py-mint has been re-branded as scikit-explain (https://github.com/monte-flora/scikit-explain). New changes to the package will be made there. If you have any questions, feel free to ask!
